version: '3.4'

services:
  dotnet-start-from-here:
    image: ${DOCKER_REGISTRY-}dotnetstartfromhere
    build:
      context: .
      dockerfile: dotnet-start-from-here/Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
  project-setup-db:
    image: postgres:latest
    container_name: Database
    environment:
      - POSTGRES_DB=projectsetup-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5432:5432
